name: Origami
version: 1.0.0
date: 2018-11-19
description: |
    Computing Veechgroups of origamis

authors:
    - name: Pascal Kattler
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Andrea Thevis
      url: http://www.math.uni-sb.de/ag/weitze/

maintainers:
    - name: Pascal Kattler
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Andrea Thevis
      url: http://www.math.uni-sb.de/ag/weitze/

GAP: "4.5.3"

needed-pkgs:
    - name: "ModularGroup"
      version: "0.0.1"
      url: "https://gap-packages.github.io/modulargroup"
    - name: "Orb"
      version: "4.7.6"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "HomalgToCAS"
      version: "2018.06.15"
      url: "http://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "IO_ForHomalg"
      version: "2017.09.02"
      url: "http://homalg-project.github.io/homalg_project/IO_ForHomalg/"
    - name: "IO"
      version: "4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "RingsForHomalg"
      version: "2018.04.04"
      url: "http://homalg-project.github.io/homalg_project/RingsForHomalg/"

www: https://PascalKattler.github.io/Origami/
readme: README.md
packageinfo: https://PascalKattler.github.io/Origami/PackageInfo.g
github: https://github.com/PascalKattler/Origami

downloads:
    - name: .tar.gz
      url: https://github.com/PascalKattler/Origami/releases/download/v1.0.0/Origami-1.0.0.tar.gz
    - name: .tar.bz2
      url: https://github.com/PascalKattler/Origami/releases/download/v1.0.0/Origami-1.0.0.tar.bz2

abstract: |
    This package calculates with origamis, a square tiled surface.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>KT18</span>]   <b class='BibAuthor'>Kattler, P. and Thevis, A.</b>,
     <i class='BibTitle'>Origami, Computing Veechgroups of origamis,
             Version 1.0.0</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://PascalKattler.github.io/Origami/">https://PascalKattler.github.io/Origami/</a></span>.
    </p>
    

bibtex: |
    @misc{ Origami1.0.0,
      author =           {Kattler, P. and Thevis, A.},
      title =            {{Origami},    Computing   Veechgroups   of   origamis,
                          {V}ersion 1.0.0},
      month =            {Nov},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href       {https://PascalKattler.github.io/Origami/}
                          {\texttt{https://PascalKattler.github.io/}\discretionary
                          {}{}{}\texttt{Origami/}}},
      printedkey =       {KT18}
    }

