#! @Chapter Functions for Dessins d'enfants
#! @ChapterLabel Functions for Dessins d'enfants

#! This section lists all functions used for Dessin d'enfants
#! @Section  Functions for Dessins d'enfants
BindGlobal("DessinFamily",NewFamily("Dessin"));
DeclareCategory("IsDessin", IsObject);
#! @Returns a permutation
#! @Arguments Dessin
#! @Description
#! This returns the horizontal permutation $\sigma_x$ of the Dessin.
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> PermX(D);
#! (1,2,3)
#! @EndExampleSession
DeclareAttribute("PermX", IsDessin);

#! @Returns a permutation
#! @Arguments Dessin
#! @Description
#! This returns the vertical permutation $\sigma_x$ of the Dessin.
#!
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> PermY(D);
#! (2,3)
#! @EndExampleSession
DeclareAttribute("PermY", IsDessin);

#! @Returns A Dessin.
#! @Arguments A pair of permutions.
#! @Description
#! This function constructs a Dessin object given by monodromy actions.
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! @EndExampleSession
DeclareOperation("Dessin", [IsPerm, IsPerm]);


#! @Returns A record.
#! @Arguments A Dessin
#! @Description
#! This function returns the valency list of a Dessin.
#! It returns a record.
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> ValencyList(D);
#! rec( black := [ 3 ], white := [ 2 ] )
#! @EndExampleSession
DeclareAttribute("ValencyList", IsDessin);

#! @Returns A non-negative integer.
#! @Arguments A Dessin.
#! @Description
#! This function calculates the genus of the Dessin, (so the genus of the underlying closed Riemann surface(?))
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! gap> Genus(D);
#! 0
#! @EndExampleSession
DeclareAttribute("Genus", IsDessin);

DeclareGlobalFunction("NormalDessinsForm");

DeclareGlobalFunction("DessinOfOrigami");

DeclareGlobalFunction("AllDessinsOfOrigami");

#! @Description
#! This calculates the degree of the Dessin surface.
#! @Returns a natural number
#! @Arguments Dessin
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> DegreeDessin(D);
#! 3
#! @EndExampleSession
DeclareAttribute("DegreeDessin", IsDessin);

#! @Description
#! This checks wheter the Dessin is connected, so wheter the group generated by $sigma_x$ and $sigma_y$ acts transitiv on [1..deg(D)]
#! @Returns A boolean.
#! @Arguments A Dessin.
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> IsConnectedDessin(D);
#! true
#! @EndExampleSession
DeclareAttribute("IsConnectedDessin", IsDessin);

#! @Description
#! This function returns the connected components of the Dessin.
#! @Returns A list.
#! @Arguments A Dessin.
#! @BeginExampleSession
#! gap> D:=Dessin((1,2,3),(2,3));
#! Dessin((1,2,3), (2,3))
#! gap> ConnectedComponentsDessin(D);
#! [ Dessin((1,2,3), (2,3)) ]
#! @EndExampleSession
DeclareGlobalFunction("ConnectedComponentsDessin");

#! @Description
#! This function returns the stable graph of an origami. It returns a list of lists.
#! The first entry is a list of the genus of the connected components of the dessin of the origami.
#! The  second entry is the adjacency matrix of the origami graph.
#! @Returns A list
#! @Arguments An Origami
#! @BeginExampleSession
#! gap>  O:=Origami((1,5,6,9,10)(3,4)(7,8)(11,12), (1,3,5,7,9,11)(2,4,10,12,6,8), 12);
#! Origami((1,5,6,9,10)(3,4)(7,8)(11,12), (1,3,5,7,9,11)(2,4,10,12,6,8), 12)
#!gap> OrigamiGraph(O);
#! [ [ 0, 1 ], [ [ 0, 1 ], [ 3, 0 ] ] ]
#! @EndExampleSession
DeclareGlobalFunction("OrigamiGraph");
